Name = str(input("Enter Your Name:"))
Age = int(input("Enter Your Age:"))
City = str(input("Enter Your City:"))
Favorite_Programming_Language = str(input("Language:"))
Dream_Company = str(input("Enter Your Dream Company:"))
Dream_Salary = float(input("Enter Your Dream Salary:"))
Current_Skill = str(input("Enter Your Skill:"))
Graduation_Year = int(input("Enter Graduation Year:"))
print("======================================")
print("        AI ENGINEER PROFILE")
print("======================================")
print("Name              :", (Name))
print("Age               :", (Age))
print("city              :", (City))
print("Language          :", (Favorite_Programming_Language))
print("Current Skill     :", (Current_Skill))
print("Dream Company     :", (Dream_Company))
print("Dream Salary      :", (Dream_Salary))
print("Graduation Year   :", (Graduation_Year))

print("======================================")